### ISSUE TITLE
devices become unavailable

### ISSUE THREAD

**Issue by nijhawank** [humbertogontijo/homeassistant-roborock#150]
It seems that the integration makes the devices unavailable after first encounter of timeout. I had the integration loaded and it was showing the devices correctly. Then after few hours, I see that both devices were unavailable. I see the following error in the logs. I had no cleanups from ha or via the app since I setup the integration.

Error fetching roborock data: Timeout after 4 waiting for response

**Comment by humbertogontijo** [comment]
Were you using this latest version?

**Comment by nijhawank** [comment]
Yes, v0.26

**Comment by Dis90** [comment]
I have same problem with latest version (0.0.26).

**Comment by Dennisd80** [comment]
I'm having the same difficulties with the latest version (0.0.26) in the log i see the following error message:

`Logger: homeassistant.config_entries
Source: custom_components/roborock/api/api.py:65
Integration: Roborock ([documentation](https://github.com/humbertogontijo/homeassistant-roborock), [issues](https://github.com/humbertogontijo/homeassistant-roborock/issues))
First occurred: 21:06:23 (1 occurrences)
Last logged: 21:06:23

Error setting up entry Roborock for roborock
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/roborock/__init__.py", line 78, in async_setup_entry
    home_data = await api_client.get_home_data(user_data)
  File "/config/custom_components/roborock/api/api.py", line 433, in get_home_data
    home_id_response = await home_id_request.request(
  File "/config/custom_components/roborock/api/api.py", line 65, in request
    async with session.request(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 466, in _request
    with timer:
  File "/usr/local/lib/python3.10/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError`

**Comment by humbertogontijo** [comment]
This is fixed in v0.0.27

**Comment by nijhawank** [comment]
I believe the original issue reported is fixed but I’m now reporting a similar related problem. I have two Roborocks and if one went offline, the integration made both roborocks unavailable

**Comment by humbertogontijo** [comment]
@nijhawank I changed the reconnection policy in v0.0.28. Are both devices still getting unavailable if one is offline in latest version?

**Comment by dsantos21** [comment]
Hi @humbertogontijo! Ive just setup this integration (v0.0.28) and I have two devices in my account (one is in use, the other is offline in its original box!).

Both showed up with this integration and one online (as expected), but now, after maybe 10 minutes, both are unavailable.
