### ISSUE TITLE
Multiple (thousands) of retries

### ISSUE THREAD

**Issue by nijhawank** [humbertogontijo/homeassistant-roborock#304]
Using mainline (commit ee18dd7) and it works fine with my two roborocks, s4 max and s7. However when one of my Roborock went offline, the integration made thousands of retries in a day of so. This is an invite to get blocked/banned by Roborock.
Can we have some way to limit the number of retries? Or increasing interval between continuous failed retries)

Logger: roborock.cloud_api
Source: custom_components/roborock/camera.py:221
Integration: Roborock (documentation, issues)
First occurred: May 8, 2023 at 7:58:26 AM (12916 occurrences)
Last logged: 3:48:25 PM
Timeout after 4 seconds waiting for response

Logger: custom_components.roborock.camera
Source: custom_components/roborock/camera.py:213
Integration: Roborock (documentation, issues)
First occurred: May 8, 2023 at 7:58:26 AM (12916 occurrences)
Last logged: 3:48:25 PM
Unable to retrieve map data

**Comment by humbertogontijo** [comment]
This should be fixed in main branch

**Comment by Lash-L** [comment]
@humbertogontijo i believe the problem they are describing still exist. They are using main. 

This is when the vacuum is offline and the coordinator will continue to retry connecting. I haven't taken a look at the best way to try to fix it

**Comment by Trebacz** [comment]
I noticed this today (on version 1.2) - This error originated from a custom integration.

Logger: custom_components.roborock.camera
Source: custom_components/roborock/camera.py:221
Integration: Roborock (documentation, issues)
First occurred: May 8, 2023 at 9:23:21 PM (29654 occurrences)
Last logged: 2:42:27 PM

Unable to retrieve map data

**Comment by Trebacz** [comment]
I'm also seeing this error now at a high rate. Not sure if they are related or seperate:
Logger: roborock.api
Source: /usr/local/lib/python3.10/site-packages/roborock/api.py:220
First occurred: 2:57:28 PM (293 occurrences)
Last logged: 3:14:03 PM

'utf-8' codec can't decode byte 0x9a in position 1: invalid start byte
'utf-8' codec can't decode byte 0xf0 in position 3: invalid continuation byte
'utf-8' codec can't decode byte 0x8c in position 0: invalid start byte
'utf-8' codec can't decode byte 0xd2 in position 3: invalid continuation byte
'utf-8' codec can't decode byte 0xc3 in position 10: invalid continuation byte
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/roborock/api.py", line 207, in on_message
    if endpoint.decode().startswith(self._endpoint):
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 0-1: invalid continuation byte

**Comment by Trebacz** [comment]
So found this in another post with instruction to download "main" vs version 1.2. Download main from HACs instead of 0.1.2. You can do that by redownloading the integration and selecting main

Three dots in the upper right hand corner of HACS, when on the Roborock integration - Select Redownload > "main" in the version list.

**Comment by Trebacz** [comment]
On version 1.0.0 I no longer have the issue. Thank you.

**Comment by humbertogontijo** [comment]
This could still be an issue through. What changed now is if it times out it will take the last known state. Could be leading to a incorrect state. Let's leave this ticket open to check how it will perform

**Comment by HabelStefan** [comment]
I still have very many timeouts which make the integration quite unusable.

Any ideas?

**Comment by nijhawank** [comment]
What I saw with update 1.0.1 was when one of my Roborock was offline, it showed the status from the other Roborock for the offline one. 
The integration is amazing and works beautifully but I always end up disabling the integration after seeing many thousands of timeouts in fear of getting banned from Roborock. I’d suggest that integration makes no more than 3 attempts to retry and afterwards only require a manual refresh by a human

**Comment by Lash-L** [comment]
Those having issues try the new 1.0.4 version

**Comment by Lash-L** [comment]
I haven't heard any issues recently in this thread - so closing for now. feel free to ping me if you are still having issues.
