### ISSUE TITLE
Map entity does not update on load_multi_map

### ISSUE THREAD

**Issue by tjafbe** [humbertogontijo/homeassistant-roborock#69]
Thanks for the awesome work ! It is great to see how quickly this integration is evolving!

When I send the load_multi_map command with the vacuum.send_command service call to change to a different floor map, the new map is immediately loaded in the app and also the attribute map_status in home assistant changes after a while representing the floor I loaded, but the actual map entity is not refreshed. Only when I start cleaning does it update. 

Would it be possible to force a map entity refresh after a load_multi_map service call? Or whenever map_status has changed?

**Comment by medfiras** [comment]
Same here

**Comment by jdejaegh** [comment]
Same, I often get timeouts after 4 seconds when changing floor via the integration.  I though it was related to #41

**Comment by Xyaren** [comment]
Same here, I also get timeouts for the `load_multi_map` command.
The app updates after a few seconds.

```
2023-01-06 18:15:12.635 DEBUG (MainThread) [custom_components.roborock] Finished fetching roborock data in 0.167 seconds (success: True)
2023-01-06 18:15:32.508 DEBUG (MainThread) [custom_components.roborock.api.api] id=31 Requesting method load_multi_map with [1]
2023-01-06 18:15:36.509 WARNING (MainThread) [custom_components.roborock.api.api] Timeout after 4 seconds waiting for load_multi_map response
```

**Comment by medfiras** [comment]
i have a workround for this issue on "cleanning" or on "returning" using this automatation on NodeRed

```json
[{"id":"9bd5bba6.b09488","type":"group","z":"a63c9be1.ee95e8","style":{"stroke":"#2e333a","stroke-opacity":"1","fill":"#2e333a","fill-opacity":"0.75","label":true,"label-position":"nw","color":"#a4a4a4"},"nodes":["bcbfcc5f.dec3d","bc974841.0bf828","d7b24b12.9306a8","cd96eee1.fadce","a843828c.34b51","ea8cb3eb.ca3dd","5f5c1f29.1e211"],"x":34,"y":39,"w":712,"h":282},{"id":"bcbfcc5f.dec3d","type":"api-call-service","z":"a63c9be1.ee95e8","g":"9bd5bba6.b09488","name":"Map Update","server":"9a0a3c87.b54a9","version":5,"debugenabled":false,"domain":"homeassistant","service":"update_entity","areaId":[],"deviceId":[],"entityId":["camera.roborock"],"data":"","dataType":"jsonata","mergeContext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":650,"y":280,"wires":[["ea8cb3eb.ca3dd","a843828c.34b51"]]},{"id":"bc974841.0bf828","type":"server-state-changed","z":"a63c9be1.ee95e8","g":"9bd5bba6.b09488","name":"Robock Docked","server":"9a0a3c87.b54a9","version":4,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"vacuum.roborock","entityidfiltertype":"exact","outputinitially":false,"state_type":"str","haltifstate":"","halt_if_type":"str","halt_if_compare":"is","outputs":1,"output_only_on_state_change":true,"for":0,"forType":"num","forUnits":"minutes","ignorePrevStateNull":false,"ignorePrevStateUnknown":false,"ignorePrevStateUnavailable":false,"ignoreCurrentStateUnknown":false,"ignoreCurrentStateUnavailable":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"},{"property":"data","propertyType":"msg","value":"","valueType":"eventData"},{"property":"topic","propertyType":"msg","value":"","valueType":"triggerId"}],"x":140,"y":280,"wires":[["cd96eee1.fadce"]]},{"id":"d7b24b12.9306a8","type":"delay","z":"a63c9be1.ee95e8","g":"9bd5bba6.b09488","name":"","pauseType":"delay","timeout":"4","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"outputs":1,"x":580,"y":160,"wires":[["bcbfcc5f.dec3d"]]},{"id":"cd96eee1.fadce","type":"switch","z":"a63c9be1.ee95e8","g":"9bd5bba6.b09488","name":"","property":"payload","propertyType":"msg","rules":[{"t":"eq","v":"cleaning","vt":"str"},{"t":"eq","v":"returning","vt":"str"}],"checkall":"true","repair":false,"outputs":2,"x":290,"y":280,"wires":[["bcbfcc5f.dec3d"],["bcbfcc5f.dec3d"]]},{"id":"a843828c.34b51","type":"api-current-state","z":"a63c9be1.ee95e8","g":"9bd5bba6.b09488","name":"cleaning","server":"9a0a3c87.b54a9","version":3,"outputs":2,"halt_if":"cleaning","halt_if_type":"str","halt_if_compare":"is","entity_id":"vacuum.roborock","state_type":"str","blockInputOverrides":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"},{"property":"data","propertyType":"msg","value":"","valueType":"entity"}],"for":0,"forType":"num","forUnits":"minutes","x":400,"y":140,"wires":[["d7b24b12.9306a8"],[]]},{"id":"ea8cb3eb.ca3dd","type":"api-current-state","z":"a63c9be1.ee95e8","g":"9bd5bba6.b09488","name":"returning","server":"9a0a3c87.b54a9","version":3,"outputs":2,"halt_if":"returning","halt_if_type":"str","halt_if_compare":"is","entity_id":"vacuum.roborock","state_type":"str","blockInputOverrides":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"},{"property":"data","propertyType":"msg","value":"","valueType":"entity"}],"for":0,"forType":"num","forUnits":"minutes","x":400,"y":200,"wires":[["d7b24b12.9306a8"],[]]},{"id":"5f5c1f29.1e211","type":"comment","z":"a63c9be1.ee95e8","g":"9bd5bba6.b09488","name":"Vacuum map update only when it is working","info":"","x":230,"y":80,"wires":[]},{"id":"9a0a3c87.b54a9","type":"server","name":"Home Assistant","addon":true}]
```

**Comment by Dis90** [comment]
Here's workaround for updating map when switching map. Use this automation and camera entity is updated after switching map.

```
alias: "Roborock: reload map"
description: ""
trigger:
  - platform: event
    event_type: call_service
    event_data:
      domain: vacuum
      service: send_command
      service_data:
        entity_id: vacuum.carlos
        command: load_multi_map
condition: []
action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - service: homeassistant.update_entity
    data: {}
    target:
      entity_id: camera.carlos_map
mode: single
```

**Comment by tjafbe** [comment]
Thanks. That's a great tip for a temporary fix.

**Comment by Xyaren** [comment]
@humbertogontijo I suspect this might be die to the implementation of non-updating-states in the camera entity?

Maybe we need a service for this command which does.an implicit update of the map after the map has been loaded?

I can see the Roborock app updating immediately when executing the command, maybe the camera can listen for such responses in a passive way as well.
Currently it is only updating when itself requested the update correct?

**Comment by humbertogontijo** [comment]
This is probably due to the camera not updating when docked. I'll create a service for this and add a valid/invalid flag for the map so it reloads

**Comment by Xyaren** [comment]
> This is probably due to the camera not updating when docked. I'll create a service for this and add a valid/invalid flag for the map so it reloads

This could still take up to 5 seconds correct?

**Comment by humbertogontijo** [comment]
I don't have more than one map to load. When I run it without params it fails. When there is more than one map there is no need to send the map id at all?

**Comment by Xyaren** [comment]
There is always the need to send a numeric index starting with 0.

**Comment by humbertogontijo** [comment]
@Xyaren can you test it with the main branch? Just made some changes that might fix it

**Comment by Xyaren** [comment]
First impression looks very good!

Just s tiny thing:
Error handling for "put of bounds" map index could be improved:

```
File "/config/custom_components/roborock/camera.py", line 242, in async_load_multi_map
await self.send(RoborockCommand.LOAD_MULTI_MAP, [map_id])
File "/config/custom_components/roborock/device.py", line 90, in send
return await self.coordinator.api.send_command(
File "/config/custom_components/roborock/api/api.py", line 295, in send_command
raise CommandVacuumError(method, err) from err
custom_components.roborock.api.exceptions.CommandVacuumError: load_multi_map: -10005: mapFlag error
```

**Comment by humbertogontijo** [comment]
I can map this code(which Im seeing that is a uint instead of int) to another message. But I need to check if it's not a generic one first

**Comment by Xyaren** [comment]
I tried to decompile the android app but unfortunately the majority of the app is based on a Google firebase app.
Someone with a rooted phone could possibly try to intercept some resources being loaded.

**Comment by tjafbe** [comment]
I just upgraded to v0.0.25. I notice there is now a new service called roborock.camera_load_multi_map. It is not clear to me how to use this service since it only accepts an entity_id, but there seems to be no way to actually pass it a parameter which floor to load? Is this service supposed to replace the generic vacuum.send_command service (with command data: load_multi_map)? If so, it should be possible to pass a parameter which floor to load? Or am I missing something?

**Comment by humbertogontijo** [comment]
@tjafbe use the main branch instead of the version in HACS
@Xyaren I've added the validation in the main branch. Check it out

**Comment by Xyaren** [comment]
Looks good!

I wonder if there is a way to attach the current room Id(flag) and name to the map entity using the map list request you just added.

Currently I‘m using a custom template sensor based on the 'room_numbers' attribute and a static mapping:

```yaml
template:                                                                      - sensor:
    - name: "Fussel loaded map"
      state: >
        {% set t = (state_attr('camera.fussel_map','room_numbers') or {}).keys() %}
        {% if 20 in t %}ground_floor                                                   {% elif 17 in t %}first_floor
          {% elif 16 in t %}attic
          {% else %}unknown{{t}}
        {% endif %}
    trigger:
      - platform: state
        entity_id: camera.fussel_map
        attribute: room_numbers
```
This might be a separate issue though ☺️

**Comment by humbertogontijo** [comment]
Closed as this is fixed in latest release

**Comment by mar1u50** [comment]
Using acuum_load_multi_map seems to work
```
service: roborock.vacuum_load_multi_map
data:
  map_flag: 0
target:
  entity_id: vacuum.roborock_s7
```

but send_command still doesn't work:
```
service: vacuum.send_command
service_data:
  command: load_multi_map
  params: 0
target:
  entity_id: vacuum.roborock_s7
```
